apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: pavel5926/devel-frontend:*
        name: frontend
        ports:
          - containerPort: 5173
            protocol: TCP
        env:
          - name: VITE_HOST
            value: "0.0.0.0"
          - name: VITE_HMR_HOST
            value: "192.168.59.112"
          - name: VITE_API_BASE_HOST
            value: "192.168.59.112"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
      nodePort: 30173
  selector:
    app: frontend
