apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: itmo-devops-manifests-2025
  namespace: flux-system
spec:
  interval: 10s
  url: ssh://git@github.com/popov-p/itmo-devops-manifests-2025.git
  ref:
    branch: master
  secretRef:
    name: flux-git-ssh