apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: frontend-automation
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: itmo-devops-manifests-2025
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: Flux Bot
        email: flux@example.com
      messageTemplate: |
        Automated image update:
        {{- range .Updated.Images }}
        - {{ .Ref }} → {{ .Policy.Tag }}
        {{- end }}

    push:
      branch: master
  update:
    path: "./"
    strategy: Setters