apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: frontends-kustomizationz
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: itmo-devops-manifests-2025
  targetNamespace: default
  prune: true
  timeout: 2m
