apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
    - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: popov
        - name: RABBITMQ_DEFAULT_USER
          value: pavel
      image: rabbitmq:3-management
      name: rabbitmq
      ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
  restartPolicy: OnFailure
  volumes:
    - name: rabbitmq-data
      persistentVolumeClaim:
        claimName: rabbitmq-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
      nodePort: 30572

    - name: "15672"
      port: 15672
      targetPort: 15672
      nodePort: 30172
  selector:
    io.kompose.service: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-data
  name: rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
