apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yml
  - backend.yml
images:
  - name: pavel5926/devel-frontend
    newName: pavel5926/devel-frontend # {"$imagepolicy": "flux-system:frontend-policy:name"}
    newTag: 1.0.103 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
  - name: pavel5926/devel-backend
    newName: pavel5926/devel-backend # {"$imagepolicy": "flux-system:backend-policy:name"}
    newTag: 1.0.102 # {"$imagepolicy": "flux-system:backend-policy:tag"}
