apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yml
images:
  - name: pavel5926/devel-frontend
    newName: pavel5926/devel-frontend # {"$imagepolicy": "flux-system:frontend-policy:name"}
    newTag: 1.0.96 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
